scheduleschemer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ssapp.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

handler404 = 'ssapp.views.RedirectIndex'

ssapp/urls.py
from django.urls import path, include
from . import views

app_name = 'ssapp'

urlpatterns = [
    path("", views.Index.as_view(), name='index'),
    path('dashboard', views.Dashboard.as_view(), name='dashboard'),
    path('curriculum', views.UserCurriculum.as_view(), name='curriculum'),
    path('course', views.UserEnrollCourse.as_view(), name='course'),
    path('ssapp/<str:pk>/profile', views.DetailProfile.as_view(), name='profile'),
    path('signup', views.Signup.as_view(), name='signup'),
#    path('curriculum/unenroll', views.unenroll_course_from_curriculum, name="unenroll_course"),

    path('ssapp/admin/dashboard', views.AdminDashboard.as_view(), name="admin_dashboard"),
    path('ssapp/admin/course', views.AdminCourse.as_view(), name="admin_course"),
    path('ssapp/admin/<str:pk>/course', views.AdminDetailCourse.as_view(), name="admin_class"),
    path("ssapp/admin/curriculum", views.AdminCurriculum.as_view(), name="admin_curriculum"),
    path("ssapp/admin/<int:pk>/curriculum", views.AdminDetailCurriculum.as_view(), name="admin_detail_curriculum"),
    path("ssapp/admin/<int:curr_id>/curriculum/generate_ge_courses", views.auto_add_ge_courses, name='add_ge_courses'),
    path("ssapp/admin/<int:curr_id>/curriculum/<str:course_id>/drop", views.drop_course_from_curriculum, name='drop_course_from_curriculum'),


]

ssapp/models.py
from django.db import models
from django.contrib.auth.models import User
from picklefield.fields import PickledObjectField
# Create your models here.
class Faculty(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return "{}".format(self.name)

class Curriculum(models.Model):
    name = models.CharField(max_length=50, unique=True)
    total_credits = models.PositiveSmallIntegerField()
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE)
    courses = models.ManyToManyField('Course', blank=True, related_name="curriculum")

    def __str__(self):
        return "{}".format(self.name)

class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='account')
    major = models.ForeignKey(Curriculum, on_delete=models.CASCADE, related_name='major', null=False)
    enrolled_class = models.ManyToManyField('ClassSchedule', blank=True, related_name="enrolled_class") 
    completed_course = models.ManyToManyField('Course', blank=True, related_name="completed_courses") 
    earned_credits = models.PositiveSmallIntegerField(default=0)
    
    def __str__(self):
        return "Username: {}".format(self.user.username)

class Course(models.Model):
    id =  models.CharField(max_length=10, primary_key=True)
    name =  models.CharField(max_length=50)
    credits = models.PositiveSmallIntegerField(default=3)
    category = models.CharField(
        choices = [
            ("General Education Courses", "General Education Courses"),
            ("Professional Courses", "Professional Courses"),
        ], max_length=30, default="Professional Courses"
    ) 
    faculty = models.ManyToManyField('Faculty', blank=True, related_name="courses")
     
    def __str__(self):
        return f"{self.id} {self.name} ({self.credits})"


class ClassSchedule(models.Model): 
    course = models.OneToOneField(Course, primary_key=True, on_delete=models.CASCADE, related_name='class_schedule') 
    availability = models.BooleanField(default=False)
    daytime = PickledObjectField(default=dict())

    def __str__(self):
        return "{}: {}".format(self.course.id, self.course.name)

class Class(models.Model): 
    id = models.CharField(max_length=10, primary_key=True)
    availability = models.BooleanField(default=False)
    daytime = PickledObjectField(default=dict())

    def __str__(self):
        return "{}".format(self.id)

ssapp/forms.py
from .models import Account, Curriculum, Course
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({
                'class': 'form-control',
            }) 

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')


class CurriculumForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CurriculumForm, self).__init__(*args, **kwargs)
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({
                'class': 'form-control',
            }) 

    class Meta:
        model = Curriculum
        fields = ('name', 'total_credits', 'faculty')
 

class UpdateCurriculumForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(UpdateCurriculumForm, self).__init__(*args, **kwargs)
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({
                'class': 'form-control',
            }) 

    class Meta:
        model = Curriculum
        fields = ['courses', ]
 
class CourseForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CourseForm, self).__init__(*args, **kwargs)
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({
                'class': 'form-control',
            }) 

    class Meta:
        model = Course 
        fields = ('id', 'name', 'credits', 'category', 'faculty')

class EnrollCourseForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(EnrollCourseForm, self).__init__(*args, **kwargs)
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({
                'class': 'form-control',
            }) 

    class Meta:
        model = Account 
        fields = ['enrolled_class',]

ssapp/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import * 
from django.contrib.auth.models import User
from .forms import * 
from django.http import Http404, JsonResponse
from picklefield.fields import PickledObjectField
from django.core import serializers
import json
from django.contrib import messages

# Create your views here.
def RedirectIndex(request, exception):
    template_name = 'ssapp/index.html' 
    messages.warning(request, "Request page is not found!")
    return render(request, template_name, {})
 
class Index(generic.TemplateView):
    template_name = 'ssapp/index.html'

class Dashboard(LoginRequiredMixin, generic.TemplateView):
    login_url = '/accounts/login'
    template_name = 'ssapp/dashboard.html' 
 
    def get(self, *args, **kwargs):
        account = Account.objects.filter(user=self.request.user)[0]
        courses = account.enrolled_class.all()
        context = {"account": account, "class_list": courses}
        if not courses:
            messages.info(self.request, "Please enroll some courses first to generate the schedule")
        return render(self.request, self.template_name, context)


class DetailProfile(LoginRequiredMixin, generic.TemplateView):
    login_url = '/accounts/login'
    template_name = 'ssapp/profile.html'
    
    def get(self, *args, **kwargs):
        account = Account.objects.filter(user=self.request.user)[0]
        courses = account.enrolled_class.all()
        register = 0
        for class_schedule in account.enrolled_class.all():
            register += class_schedule.course.credits
        total_courses = Course.objects.count()
        total_curriculum = Curriculum.objects.count()
        total_accounts = Account.objects.count()
        context = {"account": account, "courses": courses, 'register': register, 'majors': Curriculum.objects.all(), 'total_courses': total_courses, 'total_curriculum': total_curriculum, 'total_accounts': total_accounts}
        return render(self.request, self.template_name, context)
    
    def post(self, *args, **kwargs):
        print(self.request.POST)
        account = Account.objects.filter(user=self.request.user)[0]
        user = self.request.user
        fname = self.request.POST['fname']
        lname = self.request.POST['lname']
        major = self.request.POST['major']
        print(fname, lname, major, account, user)
        if len(fname):
            user.first_name = fname
        if len(lname):
            user.last_name = lname
        if len(major):
            account.major = Curriculum.objects.get(pk=major)
        user.save()
        account.save()
        messages.info(self.request, "Profile update!")
        return redirect('ssapp:profile', pk=user)

class UserCurriculum(LoginRequiredMixin, generic.TemplateView):
    login_url = '/accounts/login'
    template_name = 'ssapp/curriculum.html'
    
    def get(self, *args, **kwargs):
        account = Account.objects.filter(user=self.request.user)[0]
        ge_courses = account.major.courses.filter(category = 'General Education Courses')
        pro_courses = account.major.courses.exclude(category = 'General Education Courses')
        other_courses = account.completed_course.filter(category="Professional Courses").exclude(faculty=account.major.faculty)
        register = 0
        for class_schedule in account.enrolled_class.all():
            register += class_schedule.course.credits
        context = {"account": account, 'ge_courses': ge_courses, 'pro_courses': pro_courses, 'other_courses': other_courses, 'register': register}
        return render(self.request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        print(request.POST)
        if request.is_ajax and request.method == "POST":
            curr_acc = Account.objects.get(user=request.user)
            type = request.POST.get('type', 0)
            if type and type == 'unenroll' and request.POST.get('course_id', 0):
                course = Course.objects.get(pk=request.POST['course_id'])
                curr_acc.completed_course.remove(course)
                messages.info(request, f"{course.name} is now available to take!")
                curr_acc.save()
            if type and type == 'complete':
                course = Course.objects.get(pk=request.POST['course_id'])
                curr_acc.completed_course.add(course)
                credits = 0
                for course in curr_acc.completed_course.all():
                    credits += course.credits
                messages.info(request, f"{course.name} has been marked completed!")
                curr_acc.save()
        return JsonResponse({"instance": ""}, status=200)

class Signup(generic.CreateView):
    model = Account
    template_name = 'registration/signup.html'
    form_class = SignupForm

    def form_valid(self, form):
        self.instance = form.save(commit=False)
        username = form.cleaned_data['username']
        major = Curriculum.objects.filter(name=self.request.POST['major']).exists()
        if major:
            new_user = User.objects.create_user(username=username, password=form.cleaned_data['password1'], email=form.cleaned_data['email'], first_name=form.cleaned_data['first_name'], last_name=form.cleaned_data['last_name'])
            new_user.save()           
            major = Curriculum.objects.filter(name=self.request.POST['major'])[0]
            new_acc = Account(user=new_user, major=major)
            new_acc.save()
            messages.info(self.request, "Your account has been created successfully, please login!")        
        else:
            messages.warning(self.request, "Please select an appropriate information")
            return redirect('ssapp:signup')
        return redirect('ssapp:course')

class UserEnrollCourse(LoginRequiredMixin, generic.UpdateView):
    login_url = '/accounts/login'
    form_class = EnrollCourseForm
    template_name = 'ssapp/course.html'

    def get(self, *args, **kwargs):
        form = self.form_class()
        account = Account.objects.get(user=self.request.user)
        not_enroll_courses = account.major.courses.all()
        completed_courses = account.completed_course.all()
        not_enroll_courses = not_enroll_courses.difference(completed_courses)
        courses = account.enrolled_class.all()
        total = 0
        for one_class in courses:
            total += one_class.course.credits
        context = {"available_courses": not_enroll_courses, 'courses': courses, 'total': total}
        return render(self.request, self.template_name, context)

    def post(self, *args, **kwargs):
        if self.request.is_ajax and self.request.method == "POST":
            curr_acc = Account.objects.get(user=self.request.user)
            type = self.request.POST.get('type', 0)
            if type and type == 'unenroll' and self.request.POST.get('course_id', 0):
                course = Course.objects.get(pk=self.request.POST['course_id'])
                curr_acc.enrolled_class.remove(course.class_schedule)
                curr_acc.save()
                messages.info(self.request, f'Course {course.id} is unenroll successfully')
            if type and type == 'enroll':
                courses = self.request.POST['courses']
                if courses.find(',') > 1:
                    courses_list = courses.split(',')
                    for course in courses_list:
                        curr_acc.enrolled_class.add(Course.objects.get(pk=course).class_schedule)
                else:
                    curr_acc.enrolled_class.add(Course.objects.get(pk=courses).class_schedule)
                messages.success(self.request, f"Course {courses} is enrolled successfully!")
                curr_acc.save()
            return JsonResponse({"instance": ""}, status=200)

# Admin site
class AdminCurriculum(LoginRequiredMixin, generic.CreateView):
    login_url = '/accounts/login'
    form_class = CurriculumForm
    template_name = 'ssapp/admin/curriculum.html'

    def get(self, *args, **kwargs):
        if self.request.user.username != "admin":
            messages.warning(self.request, "You do not have admin capability")
            return redirect('ssapp:dashboard')
        all_curr = Curriculum.objects.all()
        form = self.form_class()
        context = {"all_curr": all_curr, "form": form}
        return render(self.request, self.template_name, context)

    def post(self, *args, **kwargs):
        if self.request.user.username != "admin":
            messages.warning(self.request, "You do not have admin capability")
        if self.request.is_ajax and self.request.method == "POST":
            action = self.request.POST['type']
            if action == 'add':
                form = self.form_class(self.request.POST)
                if form.is_valid():
                    instance = form.save()
                    ser_instance = serializers.serialize('json', [instance, ])
                    messages.info(self.request, f"Curriculum {self.request.POST['name']} has been created successfully")
                    return JsonResponse({"instance": ser_instance}, status=200)
                else:
                    return JsonResponse({"error": ""}, status=400)
            if action == 'delete':
                course_pk = self.request.POST['curr_pk']
                if Curriculum.objects.filter(pk=course_pk).exists():
                    curr = Curriculum.objects.get(pk=course_pk)
                    messages.info(self.request, f"Curriculum {curr.name} has been deleted successfully")
                    curr.delete()
                return JsonResponse({"instance": ""}, status=200)

class AdminDetailCurriculum(LoginRequiredMixin, generic.UpdateView):
    login_url = '/accounts/login'
    template_name = 'ssapp/admin/detail_curriculum.html'
    form_class = UpdateCurriculumForm

    def get(self, *args, **kwargs):

ssapp/templates/ssapp/admin/course.html
{% extends 'ssapp/base.html' %}
{% load static %}
{% block header_admin_course %} <span class="text-muted"> Course </span> {% endblock %}
{% block title %} Courses {% endblock %}
{% block body %}
    <div class="container py-2">
        <div class="p-5 mb-2 bg-light rounded-3">
            <div class="container-fluid py-5 mb-2">
                <h1 class="display-5 fw-bold">All Courses</h1>
                <img class="float-end" src="{% static 'images/undraw_Books_l33t.svg' %}" height="150px">
                <p class="col-md-8 fs-4 mb-4"> Manage Courses </p>
            </div>
        </div>

    </div>
    <div class="p-5">
        <h2 class="display-7 fw-bold"> Create Course </h2>
        <form id="create_course">
            {% csrf_token %}
            {{ form }} 
            <input type="submit" value="Create" class="my-2 btn btn-outline-primary">
        </form>
        <h2 class="display-7 fw-bold mt-5" >General Education Courses</h2>
        <table class="table" id="ge_table">
            <thead>
            <tr>
                <th>CourseID</th>
                <th>CourseName</th>
                <th>Credits</th>
            </tr>
            </thead>
            <tbody>
            {% for course in all_courses %}
                {% if course.category == "General Education Courses" %}
                    <tr>
                        <td><a href="{% url 'ssapp:admin_class' course.id %}">{{ course.id }}</a></td>
                        <td>{{ course.name }}</td>
                        <td>{{ course.credits }}</td>
                    </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>
        <h2 class="display-7 fw-bold mt-5">Professional Education Courses</h2>
        <table class="table" id="pro_table">
            <thead>
            <tr>
                <th>CourseID</th>
                <th>CourseName</th>
                <th>Credits</th>
            </tr>
            </thead>
            <tbody>
            {% for course in all_courses %}
                {% if course.category == "Professional Courses" %}
                    <tr>
                        <td><a href={% url 'ssapp:admin_class' course.id %}>{{ course.id }}</a></td>
                        <td>{{ course.name }}</td>
                        <td>{{ course.credits }}</td>
                    </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>


    </div>

{% endblock %}
{% block script %}
    $('#create_course').submit(function (e) {
    e.preventDefault();
    var serializedData = $(this).serialize();
    $.ajax({
    type: 'POST',
    url: "{% url 'ssapp:admin_course' %}",
    data: serializedData,
    success: function (response) {
    console.log(response);
    console.log("JSON", JSON.parse(response["instance"]));
    let instance = JSON.parse(response["instance"]);
    let curr = instance[0]["fields"];
    console.log(curr); 
    let temp = curr["category"];
    if (temp == "Professional Courses") {
        temp = "#pro_table";
        } else {
        temp = "#ge_table";
        }
    console.log(temp);
    $(`${temp} tbody`).append(
    `
    <tr>
        <td>${instance[0]["pk"]}</td>
        <td>${curr["name"]}</td>
        <td>${curr["credits"]}</td>
    </tr>
    `
    );
    Toasty("Course Creation", `Successfully created ${instance[0]["pk"]}`);
    $("#create_course").trigger('reset');
    $("#id_id").focus();

    },
    error: function(response) {
    console.log(response["responseJSON"]["error"]);
    }

    })
    })

{% endblock %}

ssapp/templates/ssapp/admin/curriculum.html
{% extends 'ssapp/base.html' %}
{% load static %}
{% block title %} Curriculum {% endblock %}
{% block header_admin_curr %} <span class="text-muted"> Curriculum </span> {% endblock %}
{% block html_head %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
{% endblock %}
{% block body %}
    <div class="container py-2">
        <div class="p-5 mb-4 bg-light rounded-3">
            <div class="container-fluid py-5 mb-2">
                <h1 class="display-5 fw-bold">Curriculum</h1>
                <img class="float-end" src="{% static 'images/undraw_Booking_re_gw4j.svg' %}" height="150px">
                <p class="col-md-8 fs-4 mb-4"> Manage Curriculum </p>
            </div>
        </div>

    </div>
    <div class="p-5">
        <div class="mb-5">
            <h2 class="display-7 fw-bold">Create Curriculum</h2>
            <form id="create_curriculum">
                {% csrf_token %}
                {{ form }} 
                <input type="hidden" name="type" value="add" />
                <input type="submit" class="mt-2 btn btn-outline-primary" value="Create" /> 
            </form>
        </div>
        <h2 class="display-7 fw-bold">List of Curriculum</h2>
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Total Credits</th>
                    <th>Faculty</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <input type="hidden" name='csrf' value='{{ csrf_token }}' />
                {% for curr in all_curr %}
                    <tr>
                        <td><a href="{% url 'ssapp:admin_detail_curriculum' curr.pk %}">{{ curr.name }} </a></td>
                        <td>{{ curr.total_credits }}</td>
                        <td>{{ curr.faculty }}</td>
                        <td> <button type="button" id="delete_{{curr.pk}}" value="{{ curr.pk }}" class="btn btn-link"><i class="bi bi-trash text-danger"></i></button></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

    </div>

{% endblock %}

{% block script %}
    $('#create_curriculum').submit(function (e) {
        e.preventDefault();
        var serializedData = $(this).serialize();
        $.ajax({
            type: 'POST',
            url: "{% url 'ssapp:admin_curriculum' %}",
            data: serializedData,
            success: function (response) {
                Toasty("Curriculum", `Creating ${$("#id_name").val()}`);
                setTimeout(()=>{location.reload()}, 1500)
            },
            error: function(response) {
                Toasty("Error", `Unable to create ${$("#id_name").val()}`);
            }

        })
    })

    $(document).on('click', '[id^=delete]', function() {
        console.log("Clicked on delete");
        let curr_id = $(this).attr('value');
        const data = {
            'type': "delete",
            'curr_pk': curr_id,
            'csrfmiddlewaretoken': $('input[name=csrf]').val()
        };
        let confirm_delete = confirm("Do you really want to delete this curriculum?");
        if (confirm_delete) {
            $.ajax({
                type: "POST",
                url: "{% url 'ssapp:admin_curriculum' %}",
                data: data,
                success: function (response) {
                    Toasty("Curriculum", `Deleting curriculum`);
                    setTimeout(()=>{location.reload()}, 1500)
                }, 
                error: function(response) {

                }

            })
        }
    })
{% endblock %}

ssapp/templates/ssapp/admin/detail_curriculum.html
{% extends 'ssapp/base.html' %}
{% load static %}
{% block html_head %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
{% endblock %}
{% block title %} {{ curriculum.name }} {% endblock %}
{% block header_admin_curriculum %} <span class="text-muted"> Curriculum </span> {% endblock %}
{% block body %}

    <div class="container py-2">
        <div class="p-5 mb-4 bg-light rounded-3">
            <div class="container-fluid py-5 mb-2">
                <h1 class="display-5 fw-bold">{{ curriculum.name }}</h1>
                <img class="float-end" src="{% static 'images/undraw_Profile_data_re_v81r.svg' %}" height="150px">
                <p class="col-md-8 fs-4 mb-4"> {{ curriculum.faculty.name }}, {{curriculum.total_credits }} credits </p>
            </div>
        </div>

    </div>
    <div class="p-5">
        <div class="mb-5">
            <h2 class="display-7 fw-bold">Add Courses</h2>
            <form id="add_course">
                {% csrf_token %}
                <select class="form-control" multiple id="id_courses" name="courses">
                    {% for option in difference_courses %}
                        <option value="{{ option.id }}">{{ option }}</option>
                    {% empty %}
                        <option>Empty</option>
                    {% endfor %}

                </select>
                <input type="submit" class="mt-2 btn btn-outline-primary" value="Add Course" /> 
            </form>
        </div>
        <h2 class="display-7 fw-bold my-2">General Education Courses</h2>
        <p class="fs-4">Maximum: 30 Credits</p>
        <div class="table-responsive">
            <button id="hide" class="btn btn-outline-secondary">Hide GE Courses?</button>
            <button id="show" class="btn btn-outline-secondary">Show GE Courses?</button>

            {% if ge_courses %}
                <table class="table table-hover" id="ge_courses">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th class="text-center">Credits</th>
                            <th class="text-center">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for course in ge_courses %}
                            <tr>
                                <td><a href="{% url 'ssapp:admin_class' course.id %}" class="">{{ course.id }}</a></td>
                                <td>{{ course.name|truncatechars:30 }}</td>
                                <td class="text-center">{{ course.credits }}</td>
                                <td class="text-center"> <a href="{% url 'ssapp:drop_course_from_curriculum' curriculum.id course.id %}" class="text-danger"><i class="bi bi-trash"></i></a> </td>
                            </tr> 
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>It seems like there is no general courses here, would you like to add all the general courses?</p>
                <a href="{% url 'ssapp:add_ge_courses' curriculum.pk %}" class="btn btn-outline-secondary">Okay please!</a>
            {% endif %}

        </div>
        <h2 class="display-7 fw-bold mt-4">Professional Courses</h2>
        <p class="fs-4">Maximum: {{ curriculum.total_credits|add:"-30" }} </p>
        <div class="table-responsive">
            <table class="table table-hover" id="professional_courses">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th class="text-center">Credits</th>
                        <th class="text-center">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% if pro_courses %}
                        {% for course in pro_courses %}
                            <tr>
                                <td><a href="{% url 'ssapp:admin_class' course.id %}">{{ course.id }}</a></td>
                                <td>{{ course.name|truncatechars:30 }}</td>
                                <td class="text-center">{{ course.credits }}</td>
                                <td class="text-center"> <a href="{% url 'ssapp:drop_course_from_curriculum' curriculum.id course.id %}" class="text-danger"><i class="bi bi-trash"></i></a> </td>
                            </tr> 
                        {% endfor %}
                    {% endif %}
                </tbody>
            </table>
        </div>

    </div>

{% endblock %}
{% block script %}
    $('#hide').click(function (e) {
        $("#ge_courses").fadeOut(300);
    })

    $('#show').click(function (e) {
        $("#ge_courses").fadeIn(300);
    })



    $('#add_course').submit(function (e) {
        let select = $("select").val()
        console.log(select);
        $("form").append(`<input type="hidden" name="courses" value=${select} multiple/>`)
        e.preventDefault();
        let url_mask = "{% url 'ssapp:admin_detail_curriculum' 12345 %}".replace(/12345/, {{ curriculum.id|safe }}); 
        var serializedData = $(this).serialize();
        $.ajax({
            type: 'POST',
            url: url_mask,
            data: serializedData,
            success: function (response) {
            location.reload();
            },
            error: function(response) {
            }

        })
        })






{% endblock %}