scheduleschemer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ssapp.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

handler404 = 'ssapp.views.RedirectIndex'

ssapp/urls.py
from django.urls import path, include
from . import views

app_name = 'ssapp'

urlpatterns = [
    path("", views.Index.as_view(), name='index'),
    path('dashboard', views.Dashboard.as_view(), name='dashboard'),
    path('curriculum', views.UserCurriculum.as_view(), name='curriculum'),
    path('course', views.UserEnrollCourse.as_view(), name='course'),
    path('ssapp/<str:pk>/profile', views.DetailProfile.as_view(), name='profile'),
    path('signup', views.Signup.as_view(), name='signup'),
#    path('curriculum/unenroll', views.unenroll_course_from_curriculum, name="unenroll_course"),

    path('ssapp/admin/dashboard', views.AdminDashboard.as_view(), name="admin_dashboard"),
    path('ssapp/admin/course', views.AdminCourse.as_view(), name="admin_course"),
    path('ssapp/admin/<str:pk>/course', views.AdminDetailCourse.as_view(), name="admin_class"),
    path("ssapp/admin/curriculum", views.AdminCurriculum.as_view(), name="admin_curriculum"),
    path("ssapp/admin/<int:pk>/curriculum", views.AdminDetailCurriculum.as_view(), name="admin_detail_curriculum"),
    path("ssapp/admin/<int:curr_id>/curriculum/generate_ge_courses", views.auto_add_ge_courses, name='add_ge_courses'),
    path("ssapp/admin/<int:curr_id>/curriculum/<str:course_id>/drop", views.drop_course_from_curriculum, name='drop_course_from_curriculum'),


]

ssapp/models.py
from django.db import models
from django.contrib.auth.models import User
from picklefield.fields import PickledObjectField
# Create your models here.
class Faculty(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return "{}".format(self.name)

class Curriculum(models.Model):
    name = models.CharField(max_length=50, unique=True)
    total_credits = models.PositiveSmallIntegerField()
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE)
    courses = models.ManyToManyField('Course', blank=True, related_name="curriculum")

    def __str__(self):
        return "{}".format(self.name)

class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='account')
    major = models.ForeignKey(Curriculum, on_delete=models.CASCADE, related_name='major', null=False)
    enrolled_class = models.ManyToManyField('ClassSchedule', blank=True, related_name="enrolled_class") 
    completed_course = models.ManyToManyField('Course', blank=True, related_name="completed_courses") 
    earned_credits = models.PositiveSmallIntegerField(default=0)
    
    def __str__(self):
        return "Username: {}".format(self.user.username)

class Course(models.Model):
    id =  models.CharField(max_length=10, primary_key=True)
    name =  models.CharField(max_length=50)
    credits = models.PositiveSmallIntegerField(default=3)
    category = models.CharField(
        choices = [
            ("General Education Courses", "General Education Courses"),
            ("Professional Courses", "Professional Courses"),
        ], max_length=30, default="Professional Courses"
    ) 
    faculty = models.ManyToManyField('Faculty', blank=True, related_name="courses")
     
    def __str__(self):
        return f"{self.id} {self.name} ({self.credits})"


class ClassSchedule(models.Model): 
    course = models.OneToOneField(Course, primary_key=True, on_delete=models.CASCADE, related_name='class_schedule') 
    availability = models.BooleanField(default=False)
    daytime = PickledObjectField(default=dict())

    def __str__(self):
        return "{}: {}".format(self.course.id, self.course.name)

class Class(models.Model): 
    id = models.CharField(max_length=10, primary_key=True)
    availability = models.BooleanField(default=False)
    daytime = PickledObjectField(default=dict())

    def __str__(self):
        return "{}".format(self.id)

ssapp/forms.py
from .models import Account, Curriculum, Course
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({
                'class': 'form-control',
            }) 

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')


class CurriculumForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CurriculumForm, self).__init__(*args, **kwargs)
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({
                'class': 'form-control',
            }) 

    class Meta:
        model = Curriculum
        fields = ('name', 'total_credits', 'faculty')
 

class UpdateCurriculumForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(UpdateCurriculumForm, self).__init__(*args, **kwargs)
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({
                'class': 'form-control',
            }) 

    class Meta:
        model = Curriculum
        fields = ['courses', ]
 
class CourseForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CourseForm, self).__init__(*args, **kwargs)
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({
                'class': 'form-control',
            }) 

    class Meta:
        model = Course 
        fields = ('id', 'name', 'credits', 'category', 'faculty')

class EnrollCourseForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(EnrollCourseForm, self).__init__(*args, **kwargs)
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({
                'class': 'form-control',
            }) 

    class Meta:
        model = Account 
        fields = ['enrolled_class',]

ssapp/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import * 
from django.contrib.auth.models import User
from .forms import * 
from django.http import Http404, JsonResponse
from picklefield.fields import PickledObjectField
from django.core import serializers
import json
from django.contrib import messages

# Create your views here.
def RedirectIndex(request, exception):
    template_name = 'ssapp/index.html' 
    messages.warning(request, "Request page is not found!")
    return render(request, template_name, {})
 
class Index(generic.TemplateView):
    template_name = 'ssapp/index.html'

class Dashboard(LoginRequiredMixin, generic.TemplateView):
    login_url = '/accounts/login'
    template_name = 'ssapp/dashboard.html' 
 
    def get(self, *args, **kwargs):
        account = Account.objects.filter(user=self.request.user)[0]
        courses = account.enrolled_class.all()
        context = {"account": account, "class_list": courses}
        if not courses:
            messages.info(self.request, "Please enroll some courses first to generate the schedule")
        return render(self.request, self.template_name, context)


class DetailProfile(LoginRequiredMixin, generic.TemplateView):
    login_url = '/accounts/login'
    template_name = 'ssapp/profile.html'
    
    def get(self, *args, **kwargs):
        account = Account.objects.filter(user=self.request.user)[0]
        courses = account.enrolled_class.all()
        register = 0
        for class_schedule in account.enrolled_class.all():
            register += class_schedule.course.credits
        total_courses = Course.objects.count()
        total_curriculum = Curriculum.objects.count()
        total_accounts = Account.objects.count()
        context = {"account": account, "courses": courses, 'register': register, 'majors': Curriculum.objects.all(), 'total_courses': total_courses, 'total_curriculum': total_curriculum, 'total_accounts': total_accounts}
        return render(self.request, self.template_name, context)
    
    def post(self, *args, **kwargs):
        print(self.request.POST)
        account = Account.objects.filter(user=self.request.user)[0]
        user = self.request.user
        fname = self.request.POST['fname']
        lname = self.request.POST['lname']
        major = self.request.POST['major']
        print(fname, lname, major, account, user)
        if len(fname):
            user.first_name = fname
        if len(lname):
            user.last_name = lname
        if len(major):
            account.major = Curriculum.objects.get(pk=major)
        user.save()
        account.save()
        messages.info(self.request, "Profile update!")
        return redirect('ssapp:profile', pk=user)

class UserCurriculum(LoginRequiredMixin, generic.TemplateView):
    login_url = '/accounts/login'
    template_name = 'ssapp/curriculum.html'
    
    def get(self, *args, **kwargs):
        account = Account.objects.filter(user=self.request.user)[0]
        ge_courses = account.major.courses.filter(category = 'General Education Courses')
        pro_courses = account.major.courses.exclude(category = 'General Education Courses')
        other_courses = account.completed_course.filter(category="Professional Courses").exclude(faculty=account.major.faculty)
        register = 0
        for class_schedule in account.enrolled_class.all():
            register += class_schedule.course.credits
        context = {"account": account, 'ge_courses': ge_courses, 'pro_courses': pro_courses, 'other_courses': other_courses, 'register': register}
        return render(self.request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        print(request.POST)
        if request.is_ajax and request.method == "POST":
            curr_acc = Account.objects.get(user=request.user)
            type = request.POST.get('type', 0)
            if type and type == 'unenroll' and request.POST.get('course_id', 0):
                course = Course.objects.get(pk=request.POST['course_id'])
                curr_acc.completed_course.remove(course)
                messages.info(request, f"{course.name} is now available to take!")
                curr_acc.save()
            if type and type == 'complete':
                course = Course.objects.get(pk=request.POST['course_id'])
                curr_acc.completed_course.add(course)
                credits = 0
                for course in curr_acc.completed_course.all():
                    credits += course.credits
                messages.info(request, f"{course.name} has been marked completed!")
                curr_acc.save()
        return JsonResponse({"instance": ""}, status=200)

class Signup(generic.CreateView):
    model = Account
    template_name = 'registration/signup.html'
    form_class = SignupForm

    def form_valid(self, form):
        self.instance = form.save(commit=False)
        username = form.cleaned_data['username']
        major = Curriculum.objects.filter(name=self.request.POST['major']).exists()
        if major:
            new_user = User.objects.create_user(username=username, password=form.cleaned_data['password1'], email=form.cleaned_data['email'], first_name=form.cleaned_data['first_name'], last_name=form.cleaned_data['last_name'])
            new_user.save()           
            major = Curriculum.objects.filter(name=self.request.POST['major'])[0]
            new_acc = Account(user=new_user, major=major)
            new_acc.save()
            messages.info(self.request, "Your account has been created successfully, please login!")        
        else:
            messages.warning(self.request, "Please select an appropriate information")
            return redirect('ssapp:signup')
        return redirect('ssapp:course')

class UserEnrollCourse(LoginRequiredMixin, generic.UpdateView):
    login_url = '/accounts/login'
    form_class = EnrollCourseForm
    template_name = 'ssapp/course.html'

    def get(self, *args, **kwargs):
        form = self.form_class()
        account = Account.objects.get(user=self.request.user)
        not_enroll_courses = account.major.courses.all()
        completed_courses = account.completed_course.all()
        not_enroll_courses = not_enroll_courses.difference(completed_courses)
        courses = account.enrolled_class.all()
        total = 0
        for one_class in courses:
            total += one_class.course.credits
        context = {"available_courses": not_enroll_courses, 'courses': courses, 'total': total}
        return render(self.request, self.template_name, context)

    def post(self, *args, **kwargs):
        if self.request.is_ajax and self.request.method == "POST":
            curr_acc = Account.objects.get(user=self.request.user)
            type = self.request.POST.get('type', 0)
            if type and type == 'unenroll' and self.request.POST.get('course_id', 0):
                course = Course.objects.get(pk=self.request.POST['course_id'])
                curr_acc.enrolled_class.remove(course.class_schedule)
                curr_acc.save()
                messages.info(self.request, f'Course {course.id} is unenroll successfully')
            if type and type == 'enroll':
                courses = self.request.POST['courses']
                if courses.find(',') > 1:
                    courses_list = courses.split(',')
                    for course in courses_list:
                        curr_acc.enrolled_class.add(Course.objects.get(pk=course).class_schedule)
                else:
                    curr_acc.enrolled_class.add(Course.objects.get(pk=courses).class_schedule)
                messages.success(self.request, f"Course {courses} is enrolled successfully!")
                curr_acc.save()
            return JsonResponse({"instance": ""}, status=200)

# Admin site
class AdminCurriculum(LoginRequiredMixin, generic.CreateView):
    login_url = '/accounts/login'
    form_class = CurriculumForm
    template_name = 'ssapp/admin/curriculum.html'

    def get(self, *args, **kwargs):
        if self.request.user.username != "admin":
            messages.warning(self.request, "You do not have admin capability")
            return redirect('ssapp:dashboard')
        all_curr = Curriculum.objects.all()
        form = self.form_class()
        context = {"all_curr": all_curr, "form": form}
        return render(self.request, self.template_name, context)

    def post(self, *args, **kwargs):
        if self.request.user.username != "admin":
            messages.warning(self.request, "You do not have admin capability")
        if self.request.is_ajax and self.request.method == "POST":
            action = self.request.POST['type']
            if action == 'add':
                form = self.form_class(self.request.POST)
                if form.is_valid():
                    instance = form.save()
                    ser_instance = serializers.serialize('json', [instance, ])
                    messages.info(self.request, f"Curriculum {self.request.POST['name']} has been created successfully")
                    return JsonResponse({"instance": ser_instance}, status=200)
                else:
                    return JsonResponse({"error": ""}, status=400)
            if action == 'delete':
                course_pk = self.request.POST['curr_pk']
                if Curriculum.objects.filter(pk=course_pk).exists():
                    curr = Curriculum.objects.get(pk=course_pk)
                    messages.info(self.request, f"Curriculum {curr.name} has been deleted successfully")
                    curr.delete()
                return JsonResponse({"instance": ""}, status=200)

class AdminDetailCurriculum(LoginRequiredMixin, generic.UpdateView):
    login_url = '/accounts/login'
    template_name = 'ssapp/admin/detail_curriculum.html'
    form_class = UpdateCurriculumForm

    def get(self, *args, **kwargs):

ssapp/templates/ssapp/base.html
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        {% load static %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" href="{% static 'images/undraw_Loading_re_5axr.svg' %}">

        <!-- Bootstrap CSS -->
        {% block html_head %}
        {% endblock %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        <title>{% block title %} Index{% endblock %} | Schedule Schemer </title>
        <style>

{% block style %}
{% endblock %}
        </style>
    </head>
    <body>
        <div class="container">
            <!-- Header -->   
            <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
                <a href="{% url 'ssapp:index' %}" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
                    <img src="{% static '/images/aiu_nb_jlogo.png' %}" height="40px">
                </a>

                <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
                    {% if request.user.username != 'admin' %}
                        <li><a href="{% url 'ssapp:index' %}" class="nav-link px-2 link-dark">{% block header_home %}Home {% endblock %}</a></li>
                        <li><a href="{% url 'ssapp:dashboard' %}" class="nav-link px-2 link-dark">{% block header_schedule %} Schedule {% endblock %}</a></li>
                        <li><a href="{% url 'ssapp:curriculum' %}" class="nav-link px-2 link-dark">{% block header_curr %} Curriculum {% endblock %}</a></li>
                    {% else %}
                        <li><a class="nav-link px-2 link-dark" href="{% url 'ssapp:admin_dashboard' %}">{% block header_admin_dashboard %} Dashboard {% endblock %}</a></li>
                        <li><a class="nav-link px-2 link-dark" href="{% url 'ssapp:admin_curriculum' %}">{% block header_admin_curr %} Curriculum {% endblock %}</a></li>
                        <li><a class="nav-link px-2 link-dark" href="{% url 'ssapp:admin_course' %}">{% block header_admin_course %} Course {% endblock %}</a></li>
                    {% endif %}
                </ul>

                <div class="col-md-3 text-end">
                    {% if user.is_authenticated %}
                        <a href="{% url 'ssapp:profile' request.user %}" class="btn {% block header_style_profile %}btn-outline-primary {% endblock %} me-2 mb-1" style="width: 6.5em !important"> Profile </a>
                        <a href="{% url 'logout' %}" class="btn me-2 mb-1 {% block header_style_signout %} btn-danger {% endblock %}" style="width: 6.5em !important">SIGN OUT</a>
                    {% else %}
                        <a href="{% url 'login' %}" class="btn btn-primary me-2 mb-1"  style="width: 5.8em !important">SIGN IN</a>
                        <a href="{% url 'ssapp:signup' %}" class="btn btn-outline-secondary me-2 mb-1 ">SIGN UP</a>

                    {% endif %}
                </div>
            </header>
        </div> 
        {# Alert #}
        <div class="position-fixed bottom-0 end-0 p-3" style="z-index: 5;">
            <div id="liveToast" class="toast hide" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="toast-header">
                    <img src="{% static 'images/undraw_collecting_fjjl.svg' %}" width="30px" class="rounded me-2" alt="...">
                    <strong class="me-auto">{% block status %}<span id="status" class="text-uppercase">Status</span>{% endblock %}</strong>
                    <small>Message</small>
                    <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
                <div class="toast-body">
                    {% block alert %} <span id="message">hello there</span> {% endblock %}
                </div>
            </div>
        </div>

        <div class="container container-fluid">
            {% block body %} Hello World
            {% endblock %}
        </div>
        {# Foot #}
        <div class="mt-4">
            <footer class="footer mt-auto py-3 bg-light">
                <div class="container text-center">
                    <span class="text-muted"> <a href="mailto:chanrose@pm.me"> Found Bug ? </a> <br />  Andreas - Broset - Bryan - Yilin <br /> Alright reserved 2021 <br /> Special thanks to <br /> Josh, Dan, Abel</span>
                </div>
            </footer>
        </div>
        {% block load_jquery %} <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script> {% endblock %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script> 
        <script>
            const option_toast = 
                {
                    animation : true,
                    delay : 2000
                };

            function Toasty(status, message)
            {
                document.getElementById('status').innerHTML = status;
                document.getElementById('message').innerHTML = message; 
                var toastHTMLElement = document.getElementById( 'liveToast' ); 
                console.log(toastHTMLElement)
                var toastElement = new bootstrap.Toast( toastHTMLElement, option_toast ); 
                toastElement.show( );
            }


            {% block script %}
            {% endblock %}
        </script>

        {% if messages %}
            <script>
                {% for message in messages %}
                    Toasty("{{ message.tags }}", "{{ message }}");
            {% endfor %}
            </script>
        {% endif %}
    </body>
</html>

ssapp/templates/ssapp/profile.html
{% extends 'ssapp/base.html' %}
{% load static %}
{% block title %} Profile {% endblock %}
{% block header_style_profile %} btn btn-primary {% endblock %}
{% block header_style_signout %} btn-outline-danger {% endblock %}
{% block body %}
    <main>
        <div class="container py-2">
            <div class="p-5 mb-4 bg-light rounded-3">
                <div class="container-fluid py-5 mb-2">
                <h1 class="display-5 fw-bold"> {% if request.user.username != "admin" %} {{ request.user.first_name }} {{ request.user.last_name }} {% else %} {{ request.user }} {% endif %}</h1>

                <img class="float-end" src="{% static 'images/undraw_Growing_re_olpi.svg' %}" height="140px">
            <p class="col-md-6 fs-4 mb-4">{% if request.user.username != "admin" %}{{ account.major }} {% else %} Registrar Office {% endif %}</p>
                </div>
            </div>

            <div class="row align-items-md-stretch">
                <div class="col-md-6">
                    <div class="h-100 p-5 text-white bg-dark rounded-3">
                        {% if request.user.username != "admin" %}
                            <h2>Study Completion</h2>
                            <ul>
                                <li>Register Credits: {{ register }}</li>
                                <li>Accumulated Credits: {{ account.earned_credits }}</li>
                                <li>Required Credits: {{ account.major.total_credits }}</li>
                            </ul>
                        {% else %}
                            <h2>Actions</h2>
                            <p> <a href="{% url 'ssapp:admin_course' %}" class="btn btn-light">Open Courses</a> | <a href="{% url 'ssapp:admin_curriculum' %}" class="btn btn-light">Open Curriculum</a></p>

                        {% endif %}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="h-100 p-5 bg-light border rounded-3">
                        {% if request.user.username != "admin" %}
                            <h2>Enrolled Classes:</h2>
                            <ul class="list-group list-unstyled">
                                {% for class in courses %}
                                    <li>{{ class.course.id }} {{ class.course.name }}</li>
                                {% empty %}
                                    <li>
                                        You haven't enroll in any courses yet!
                                    </li>
                                {% endfor %}
                            </ul>
                            <a class="btn btn-outline-dark mt-2" href="{% url 'ssapp:course' %}">Open Classes</a>
                        {% else %}
                            <h2>Status:</h2>
                            <li>Total courses: {{ total_courses }}</li>
                            <li>Total curriculum: {{ total_curriculum }}</li>
                            <li>Total accounts: {{ total_accounts }}</li>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="row align-items-md-stretch mt-4">
                <div class="col-md-6">
                    <div class="h-100 p-5 text-dark bg-light border rounded-3">
                        {% if request.user.username != "admin" %}     <h2>Update</h2>
                            <form id="update_profile" method="POST">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col">
                                        <label for="fname">First Name</label>
                                        <input type="text" id="fname" value="{{ request.user.firstname }}" name="fname" class="form-control"/>
                                    </div>
                                    <div class="col">
                                        <label for="lname">Last Name</label>
                                        <input type="text" id="lname" value="{{ request.user.lastname }}" name="lname" class="form-control"/>
                                    </div>
                                </div>
                                <label for='major'>Major</label>
                                <select id="major" name="major" class="form-control">
                                    <option value="{{ account.major.pk }}">---</option>
                                    {% for major in majors %}
                                        <option value="{{ major.pk }}"> {{ major.name }}</option>
                                    {% endfor %} 
                                </select>
                                <div class="text-end">
                                    <input type="submit" value="Update" class="btn btn-outline-danger my-1" />
                                </div>

                            </form>
                        {% else %}
                            <h2>Update</h2>
                            <p>Update is not available for admin</p>

                        {% endif %}

                    </div>
                </div>
                <div class="col-md-6">
                    <div class="h-100 p-5 bg-dark text-light rounded-3">
                        <img src="{% static 'images/undraw_Profile_data_re_v81r.svg' %}" class="img-fluid" />
                    </div>
                </div>
            </div>


        </div>

    </main>

{% endblock %}